spring:
  application:
    name: payment-authorization-switch
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/paymentswitch}
    username: ${SPRING_DATASOURCE_USERNAME:paymentswitch}
    password: ${SPRING_DATASOURCE_PASSWORD:paymentswitch}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

switch:
  per-transaction-limit-minor-units: 500000

management:
  endpoints:
    web:
      exposure:
        include: health,info
